name: businesslibrary
description: Data model Package for Business Finance Network apps
version: 1.0.1
author: Aubrey Malabie Esq.<aubrey@aftarobot.com>
homepage: http://aftarobot.com

environment:
  sdk: '<3.0.0'

dependencies:
    cupertino_icons: ^0.1.2
    uuid: ^1.0.3
    font_awesome_flutter: ^8.2.0
    google_sign_in: ^3.2.4
    firebase_auth: ^0.6.6
    firebase_messaging: ^2.1.0
    firebase_storage: ^1.0.4
    firebase_remote_config: ^0.0.6+1
    cloud_firestore: ^0.8.2+3
    shared_preferences: ^0.4.3
    path_provider: ^0.4.1
    json_annotation: ^1.1.0
    intl: ^0.15.7
    web_socket_channel: ^1.0.9
    email_validator: ^1.0.0
    colorize: ^2.0.0
    http: ^0.12.0
    swipedetector: ^1.2.0
    charts_flutter: ^0.5.0
    crypto: ^2.0.6
    crypt: ^1.0.7
    flutter_webview_plugin: ^0.3.0+2
    scoped_model: ^0.3.0
    device_info: ^0.3.0

#    oktoast: ^1.0.1+2
#    card_settings: ^0.1.10
#    flutter_staggered_grid_view: ^0.2.2
#    charts_flutter: ^0.4.0
#    fluttertoast: ^2.0.7
#    fancy_on_boarding: ^0.0.2
#    date_format: ^1.0.5
#    flutter_swiper: ^1.0.4
#    animated_text_kit: ^1.0.3
#    flutter_local_notifications: ^0.3.3


dev-dependencies:
  build_runner: ^0.8.9
  json_serializable: ^0.5.7
  dart_style: ^1.0.10
