name: businesslibrary
description: Data model Package for Business Finance Network apps
version: 1.0.1
author: Aubrey Malabie Esq.<aubrey@aftarobot.com>
homepage: http://aftarobot.com

environment:
  sdk: '<3.0.0'

dependencies:
    cupertino_icons: ^0.1.2
    uuid: ^1.0.3
    font_awesome_flutter: ^8.2.0
    google_sign_in: ^4.0.1+3
    firebase_auth: ^0.8.4+5
    firebase_messaging: ^4.0.0+4
    firebase_storage: ^2.1.1+1
    cloud_firestore: ^0.10.0
    shared_preferences: ^0.5.2
    path_provider: ^0.5.0+1
    jaguar_serializer: ^2.2.8
    intl: ^0.15.8
    http: ^0.12.0+2
    web_socket_channel: ^1.0.9
    email_validator: ^1.0.0
    unicorndial: ^1.1.5
    colorize: ^2.0.0
    swipedetector: ^1.2.0
    charts_flutter: ^0.5.0
    crypto: ^2.0.6
    crypt: ^1.0.7
    flutter_webview_plugin: ^0.3.0+2
    device_info: ^0.3.0
    intro_views_flutter: ^2.4.0
    google_maps_flutter: ^0.5.7
    build_runner:
    jaguar_serializer_cli:
    url_launcher:
      git:
        url: git://github.com/flutter/plugins
        path: packages/url_launcher

dev-dependencies:
  build_runner:
  jaguar_serializer_cli:
  dart_style: ^1.2.3
  mockito: ^3.0.0
