name: businesslibrary
description: Data model Package for Business Finance Network apps
version: 0.0.179
author: Aubrey Malabie <aubrey@aftarobot.com>
homepage: http://aftarobot.com

#environment:
#  sdk: '>=1.23.4 <2.0.0'

dependencies:
    cupertino_icons: ^0.1.2
    uuid: ^1.0.3
    font_awesome_flutter: ^7.1.0
    google_sign_in: ^3.0.3
    firebase_auth: ^0.5.18
    firebase_database: ^1.0.3
    firebase_messaging: ^1.0.4
    firebase_storage: ^1.0.1
    firebase_remote_config: ^0.0.5
    cloud_firestore: ^0.7.4
    shared_preferences: ^0.4.0
    path_provider: ^0.4.1
    json_annotation: ^1.1.0
    intl: ^0.15.7
    http: ^0.11.3+16
#    oktoast: ^1.0.1+2
#    card_settings: ^0.1.10
#    flutter_staggered_grid_view: ^0.2.2
#    charts_flutter: ^0.4.0
#    fluttertoast: ^2.0.7
#    fancy_on_boarding: ^0.0.2
#    date_format: ^1.0.5
#    flutter_swiper: ^1.0.4
#    animated_text_kit: ^1.0.3
#    flutter_local_notifications: ^0.3.3


dev-dependencies:
  build_runner: ^0.8.9
  json_serializable: ^0.5.7
  dart_style: ^1.0.10
