name: businesslibrary
description: Data model Package for Business Finance Network apps
version: 0.0.31
author: Aubrey Malabie <aubrey@aftarobot.com>
homepage: http://aftarobot.com

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
    uuid: "^1.0.0"
    http: "^0.11.3+16"
