name: supplier
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  businesslibrary: ^0.0.49
  font_awesome_flutter: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
         - assets/fincash.jpg
         - assets/fin3.jpeg
  fonts:
        - family: Raleway
          fonts:
            - asset: fonts/Raleway-Regular.ttf
            - asset: fonts/Raleway-Italic.ttf
            - asset: fonts/Raleway-ExtraBold.ttf
            - asset: fonts/Raleway-Bold.ttf
        - family: RobotoMono
          fonts:
            - asset: fonts/Roboto-Regular.ttf
            - asset: fonts/Roboto-Bold.ttf
        - family: Rubik
          fonts:
            - asset: fonts/Rubik-Regular.ttf
            - asset: fonts/Rubik-Bold.ttf
            - asset: fonts/Rubik-Black.ttf
            - asset: fonts/Rubik-Light.ttf
            - asset: fonts/Rubik-Italic.ttf
            - asset: fonts/Rubik-Medium.ttf
